trigger:
- main

pool:
  name: Default

variables: 
  dockerRegistry: 'localhost:5000'

steps:
- task: Gradle@4
  displayName: 'Gradle Build'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
  
- task: Gradle@4
  displayName: 'Gradle Dockerize'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'dockerize'
    options: '-Ppersistence=true'

- script: |
    docker tag sts:latest $(dockerRegistry)/sts:latest
    docker push $(dockerRegistry)/sts:latest
  displayName: 'Push sts docker image to docker registry'

- script: |
    docker tag identity-hub:latest $(dockerRegistry)/identity-hub:latest
    docker push $(dockerRegistry)/identity-hub:latest
  displayName: 'Push identity hub docker image to docker registry'

- script: |
    docker tag controlplane:latest $(dockerRegistry)/controlplane:latest
    docker push $(dockerRegistry)/controlplane:latest
  displayName: 'Push controlplane docker image to docker registry'

- script: |
    docker tag dataplane:latest $(dockerRegistry)/dataplane:latest
    docker push $(dockerRegistry)/dataplane:latest
  displayName: 'Push dataplane docker image to docker registry'

- script: |
    docker image rm sts:latest
    docker image rm localhost:5000/sts 

    docker image rm identity-hub:latest
    docker image rm localhost:5000/identity-hub:latest 
    
    docker image rm controlplane:latest
    docker image rm localhost:5000/controlplane:latest

    docker image rm dataplane:latest
    docker image rm localhost:5000/dataplane:latest
  displayName: 'Cleanup local docker images'