trigger:
- main

pool:
  name: Default

steps:
- task: Gradle@4
  displayName: 'Gradle Build'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
  
- task: Gradle@4
  displayName: 'Gradle Dockerize'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'dockerize'
    options: '-Ppersistence=true'
