trigger:
- main

pool:
  name: Default

variables: 
  dockerRegistry: 'localhost:5000'

steps:
- task: Gradle@4
  displayName: 'Gradle Build'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
  
- task: Gradle@4
  displayName: 'Gradle Dockerize'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'dockerize'
    options: '-Ppersistence=true'

- script: |
    docker tag sts:latest $(dockerRegistry)/sts:latest
    docker push $(dockerRegistry)/sts:latest
  displayName: 'Push sts docker image to docker registry'